### ISSUE TITLE
Handling of allOf types

### ISSUE THREAD

**Issue by javagl** [CesiumGS/wetzel#29]
While trying to do a seemingly simple fix ( https://github.com/KhronosGroup/glTF/issues/1013 ), I noticed that the issue refers to other properties as well. 

The general question is: How are `allOf` type definitions supposed to be handled? 

In a [recent issue in glTF](https://github.com/KhronosGroup/glTF/issues/1144#issuecomment-355821321), people argued that *true* multiple inheritance should not be allowed in glTF anyhow. Nevertheless, even for *single* inheritance, the types are listed in an `allOf` property. 

In many cases, this is not so critical - specifically, for glTF, because `glTFProperty`, `glTFChildOfRootProperty` and `glTFid` are usually omitted via the command line or boil down to `object`/`integer` anyhow. But for other properties (`textureInfo`, `camera.orthographic`, `material.pbrMetallicRoughness` etc) this is relevant.

I think that it could be easy to fix it for the cases where `allOf` only contains a single element. I could add a check in https://github.com/AnalyticalGraphicsInc/wetzel/blob/46878d1f97c132ed7a01a3c05dedd6ec119d3c7e/lib/generateMarkdown.js#L472 , roughly like

    if (property.has("allOf")) {
        if (property.allOf.length != 0) printSomeWarning(?);
        else return property.allOf[0].type;
    }

Otherwise, it would be necessary to pass not a single `type` (and `formattedType`) through the downstream pipeline, but always use a `types[]` array, including some contortions for properly generating the bullet point lists in the markdown for the property detail descriptions ... 

Would it be OK to assume that `allOf` only contains a single type, and `console.log` a warning otherwise? 

(One could also add this warning somewhere in https://github.com/AnalyticalGraphicsInc/wetzel/blob/46878d1f97c132ed7a01a3c05dedd6ec119d3c7e/lib/schema4Resolver.js#L79 , if this is the preferred way...)

**Comment by emackey** [comment]
I think this issue is obsolete given the new glTF spec.
