### ISSUE TITLE
Update README.md to account for JSON Schema 4

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/wetzel#6]
@HowardWolosky could you please make this small change to the doc and example in the [README.md](https://github.com/AnalyticalGraphicsInc/wetzel/blob/master/README.md)?

We missed it in #4.

**Comment by HowardWolosky** [comment]
It wasn't missed.  It was just already part of the next PR that I'm about to send.

**Comment by pjcozzi** [comment]
Very nice, thanks!
